### ISSUE TITLE
converting from PT to NZST gives one hour later 

### ISSUE THREAD

**Issue by jerobarraco** [dommmel/mytime.io#1]
As of today 
2pm PT reported as 10 am Nzst instead of 9am

**Comment by dommmel** [comment]
Note: This is likely caused within the [TimezoneParser](https://github.com/davispuh/TimezoneParser) < 1.0.0 gem. Not sure upgrading it to 1.0.0 is possible as the gem seems to [require sqlite now](https://github.com/davispuh/TimezoneParser/commit/f13608d13418777353e8f27f5bac07e48f75c65c) which I don't think will work out of the box with the current heroku deployment.
