### ISSUE TITLE
Unable to use the kinda sort of an API

### ISSUE THREAD

**Issue by fd1911** [dommmel/mytime.io#3]
Hello team, maybe bacause i'm a newbie but I tried to use the API on a micro website that I have but on the chrome console says this:
```
Access to XMLHttpRequest at 'http://mytime.io/19:00/UTC-03:00' from origin 'http://127.0.0.1:5500' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
test.html:76 GET http://mytime.io/19:00/UTC-03:00 net::ERR_FAILED 200
```
My code is:

```
<p style='font-family: Montserrat;'>•	From monday to friday at 19:00 Hs, wich in your timezone is:</p>
<div data-mytime='19:00/UTC-03:00' data-mytime-showtimezone='true'>
loading..</div>
<script type='text/javascript' src='http://mytime.io/lib.js'></script>

```
And the text is stuck at loading.

Can I get a hint?

Thanks!

**Comment by dommmel** [comment]
Indeed, the app needs CORS support. Thanks for catching this. 
It wasn't a problem when I created this but nowadays modern web browsers enforce CORS. Will gladly merge a PR regarding that fixes it.

**Comment by fd1911** [comment]
Hey! Thanks for the response. Indeed i wasn't for the first time wrong hahahah.
I'm an absolute newbie into web design, been working in the IT industry as a Sysadmin but never touched a single line of code.

Thanks!

**Comment by dommmel** [comment]
Actually, I think removing the API/lib stuff makes more sense than fixing it.
