### ISSUE TITLE
Use 24-hour clock

### ISSUE THREAD

**Issue by boxed** [dommmel/mytime.io#4]
AM/PM is confusing. The entire point of this page is to be super clear about what time it it, and 24 hour clock is much clearer!

You could show both too, that's a good solution too.

**Comment by dommmel** [comment]
It actually does kind of work with 24h format. It should depend on your browser settings.

Here is what I see when visiting: http://mytime.io/02:35/PST
<img width="766" alt="Screenshot 2022-03-09 at 09 45 52" src="https://user-images.githubusercontent.com/15915/157405275-f2dc5d64-19fc-4b6a-9946-9e1046a630ca.png">

Or do you mean the analog watches? Anyway, happy to accept (well done) PRs.

**Comment by boxed** [comment]
Oh. Interesting! I have my mac set to US English but the time format to 24 hour format. I guess that doesn't translate over well.
